name: ILP PacBio single genes

on:
  workflow_dispatch:

env:
  RUN_NAME: ILP.PB
  LAUNCHER: ${{github.workspace}}/tests/github/run_pipeline.py
  CFG_DIR: /abga/work/andreyp/ci_isoquant/data
  BIN_PATH: /abga/work/andreyp/ci_isoquant/bin/
  OUTPUT_BASE: /abga/work/andreyp/ci_isoquant/output/${{github.ref_name}}/

jobs:
  launch-runner:
    runs-on:
      labels: [self-hosted]
    name: 'Running IsoQuant and QC'

    steps:
      - name: 'Cleanup'
        run: >
          set -e &&
          shopt -s dotglob &&
          rm -rf *

      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'ILP PacBio Camk2b'
        shell: bash
        env:
          STEP_NAME: ILP.PB.Camk2b
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.RUN_NAME}}.cfg -o ${{env.OUTPUT_BASE}}

      - name: 'ILP PacBio BIN1'
        shell: bash
        env:
          STEP_NAME: ILP.PB.BIN1
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.RUN_NAME}}.cfg -o ${{env.OUTPUT_BASE}}
