name: Resume option tests

on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 * * 2,5'

env:
  RUN_NAME: Resume_tests
  LAUNCHER: ${{github.workspace}}/tests/github/run_pipeline.py
  CFG_DIR: /abga/work/andreyp/ci_isoquant/data
  BIN_PATH: /abga/work/andreyp/ci_isoquant/bin/
  OUTPUT_BASE: /abga/work/andreyp/ci_isoquant/output/${{github.ref_name}}/

jobs:
  launch-runner:
    runs-on:
      labels: [self-hosted]
    name: 'Running IsoQuant and QC'

    steps:
      - name: 'Cleanup'
        run: >
          set -e &&
          shopt -s dotglob &&
          rm -rf *

      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Resume from assignment step'
        if: always()
        shell: bash
        env:
          STEP_NAME: RESUME1.SIRVs.R10
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.STEP_NAME}}.cfg -o ${{env.OUTPUT_BASE}}

      - name: 'Resume from construction step'
        if: always()
        shell: bash
        env:
          STEP_NAME: RESUME2.SIRVs.R10
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.STEP_NAME}}.cfg -o ${{env.OUTPUT_BASE}}

      - name: 'Resume from multimapper step'
        if: always()
        shell: bash
        env:
          STEP_NAME: RESUME3.SIRVs.R10
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.STEP_NAME}}.cfg -o ${{env.OUTPUT_BASE}}

      - name: 'Resume from assignment step with additional options'
        if: always()
        shell: bash
        env:
          STEP_NAME: RESUME4.SIRVs.R10
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.STEP_NAME}}.cfg -o ${{env.OUTPUT_BASE}}

      - name: 'Resume from assignment step with 2 files'
        if: always()
        shell: bash
        env:
          STEP_NAME: RESUME_GR1.SIRVs.R10
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.STEP_NAME}}.cfg -o ${{env.OUTPUT_BASE}}

      - name: 'Resume from assignment step with TSV groups'
        if: always()
        shell: bash
        env:
          STEP_NAME: RESUME_GR2.SIRVs.R10
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.STEP_NAME}}.cfg -o ${{env.OUTPUT_BASE}}

