name: SIRVs simulated R9

on:
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * 4'

env:
  RUN_NAME: SIRVs.simulated
  LAUNCHER: ${{github.workspace}}/tests/github/run_pipeline.py
  CFG_DIR: /abga/work/andreyp/ci_isoquant/data
  BIN_PATH: /abga/work/andreyp/ci_isoquant/bin/
  OUTPUT_BASE: /abga/work/andreyp/ci_isoquant/output/${{github.ref_name}}/

jobs:
  launch-runner:
    runs-on:
      labels: [self-hosted]
    name: 'Running IsoQuant and QC'

    steps:
      - name: 'Cleanup'
        run: >
          set -e &&
          shopt -s dotglob &&
          rm -rf *

      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'SIRVs simulated ONT R9'
        shell: bash
        env:
          STEP_NAME: SIRVs.simulated_R9_real_exp
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.RUN_NAME}}.cfg -o ${{env.OUTPUT_BASE}}

      - name: 'SIRVs simulated ONT R9 real expression'
        shell: bash
        env:
          STEP_NAME: SIRVs.simulated_R9_real_exp
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.RUN_NAME}}.cfg -o ${{env.OUTPUT_BASE}}
