name: SIRVs simulated R10

on:
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * 6'

env:
  RUN_NAME: SIRVs.simulated
  LAUNCHER: ${{github.workspace}}/tests/github/run_pipeline.py
  CFG_DIR: /abga/work/andreyp/ci_isoquant/data
  BIN_PATH: /abga/work/andreyp/ci_isoquant/bin/
  OUTPUT_BASE: /abga/work/andreyp/ci_isoquant/output/${{github.ref_name}}/

jobs:
  launch-runner:
    runs-on:
      labels: [self-hosted]
    name: 'Running IsoQuant and QC'

    concurrency:
      group: $env.RUN_NAME
      cancel-in-progress: false

    steps:
      - name: 'Cleanup'
        run: >
          set -e &&
          shopt -s dotglob &&
          rm -rf *

      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'SIRVs.simulated_R10'
        if: always()
        shell: bash
        env:
          STEP_NAME: SIRVs.simulated_R10
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.STEP_NAME}}.cfg -o ${{env.OUTPUT_BASE}}

      - name: 'SIRVs.simulated_R10_no_trunc'
        if: always()
        shell: bash
        env:
          STEP_NAME: SIRVs.simulated_R10_no_trunc
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.STEP_NAME}}.cfg -o ${{env.OUTPUT_BASE}}

      - name: 'SIRVs.simulated_R10_real_exp'
        if: always()
        shell: bash
        env:
          STEP_NAME: SIRVs.simulated_R10_real_exp
        run: |
          export PATH=$PATH:${{env.BIN_PATH}}
          python3 ${{env.LAUNCHER}} ${{env.CFG_DIR}}/${{env.STEP_NAME}}.cfg -o ${{env.OUTPUT_BASE}}
